vich_uploader:
    db_driver: orm
    metadata:
       type: attribute

    mappings:
        voiture_images:
          uri_prefix: /images/voiture
          upload_destination: '%kernel.project_dir%/public/images/voiture'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
